import { Quote, LandingTexts, WebsiteStyles } from "./types";

export const DEFAULT_WEBSITE_STYLES: WebsiteStyles = {
  "serifFont": "EB Garamond",
  "bodyFont": "Inter",
  "bgColor": "#0f0100",
  "textColor": "#ffffff",
  "accentColor": "#d7b9b9",
  "formBgColor": "#5a0600",
  "quoteSize": "23px",
  "hookSize": "text-lg sm:text-xl",
  "showCountdown": true,
  "showBorderFrame": true,
  "showCursiveVibe": true,
  "borderThickness": "0px",
  "logoText": "Maktabah Alkutawi",
  "logoType": "image",
  "logoImageUrl": "https://i.postimg.cc/ZnCzKvdd/SURAT-SURAT-AISHA-HAMDAN-(1).png",
  "logoSize": "500px",
  "logoWeight": "semibold",
  "logoStyle": "normal",
  "upperTagFont": "Inter",
  "upperTagSize": "10px",
  "upperTagColor": "#ffffff",
  "countdownFont": "EB Garamond",
  "countdownSize": "14px",
  "countdownColor": "#ffffff",
  "countdownLabelFont": "Inter",
  "countdownLabelSize": "10px",
  "countdownLabelColor": "#e9dddd",
  "logoFont": "EB Garamond",
  "logoColor": "#ffffff",
  "quoteFont": "EB Garamond",
  "quoteColor": "#ffffff",
  "cursiveFont": "Allison",
  "cursiveSize": "40px",
  "cursiveColor": "#ecc3bf",
  "formTitleFont": "EB Garamond",
  "formTitleSize": "20px",
  "formTitleColor": "#ffffff",
  "formDescFont": "Space Grotesk",
  "formDescSize": "12px",
  "formDescColor": "#ecc3bf",
  "footerFont": "EB Garamond",
  "footerSize": "11px",
  "footerColor": "#ffffff",
  "aboveLogoFont": "Cinzel",
  "aboveLogoSize": "12px",
  "aboveLogoColor": "#ecc3bf",
  "belowLogoFont": "EB Garamond",
  "belowLogoSize": "18px",
  "belowLogoColor": "#ffffff",
  "launchFont": "Playfair Display",
  "launchSize": "10px",
  "launchColor": "#f5ebe6",
  "launchIcon": "Globe",
  "launchIconUrl": "",
  "launchIconSize": "15px",
  "launchIconYOffset": "0px",
  "publisherFont": "Playfair Display",
  "publisherSize": "10px",
  "publisherColor": "#f5ebe6",
  "publisherIcon": "Library",
  "publisherIconUrl": "https://i.postimg.cc/65CBdbLC/Untitled-design2.png",
  "publisherIconSize": "20px",
  "publisherIconYOffset": "-2px",
  "headerBgColor": "#c4a7a6",
  "globalAlignment": "center",
  "spacingPageTop": "40px",
  "spacingAboveLogo": "16px",
  "spacingLogo": "17px",
  "spacingBelowLogo": "16px",
  "spacingQuotes": "16px",
  "spacingCursive": "16px",
  "spacingBlocks": "20px",
  "logoUnderCursiveUrl": "https://i.postimg.cc/HLt8fHNt/Untitled-design-(2).png",
  "logoUnderCursiveSize": "64px",
  "audioUrl": "",
  "audioTitle": "Latar Suasana (Ambient Audio)",
  "audioEnabled": false,
  "googleSheetsWebhookUrl": "",
  "embedIframeEnabled": true,
  "embedIframeCode": "<iframe src=\"https://drive.google.com/file/d/1NqQSgXq13CrPclcf6cc9NLcKJb8vDtVL/view\" width=\"640\" height=\"480\"></iframe>",
  "embedIframeTitle": "Semusim Cinta di Mu'tah (Draf OST)",
  "embedIframeWidth": "max-w-2xl",
  "embedIframeHeight": "34px",
  "embedIframePlayOnly": false,
  "footerBgColor": "#000000",
  "footerShowBorder": true,
  "copyrightFont": "Space Grotesk",
  "copyrightSize": "10px",
  "copyrightColor": "rgba(255, 255, 255, 0.4)",
  "tabTitle": "Surat-surat Aisha Hamdan",
  "mobileSpacingPageTop": "40px",
  "mobileSpacingAboveLogo": "0px",
  "mobileSpacingLogo": "0px",
  "mobileSpacingBelowLogo": "0px",
  "mobileSpacingQuotes": "16px",
  "mobileSpacingCursive": "16px",
  "mobileSpacingBlocks": "20px",
  "mobileLogoSize": "350px",
  "mobileCursiveSize": "28px",
  "mobileFormTitleSize": "20px",
  "mobileFormDescSize": "12px",
  "mobileUpperTagSize": "8px",
  "mobileCountdownSize": "14px",
  "mobileCountdownLabelSize": "10px",
  "mobileQuoteSize": "text-lg",
  "mobileHookSize": "text-lg sm:text-xl",
  "mobileAboveLogoSize": "12px",
  "mobileBelowLogoSize": "15px",
  "mobileFooterSize": "11px",
  "mobileLaunchSize": "10px",
  "mobilePublisherSize": "10px",
  "mobileLaunchIconSize": "15px",
  "mobileLaunchIconYOffset": "0px",
  "mobilePublisherIconSize": "20px",
  "mobilePublisherIconYOffset": "-2px",
  "mobileSpotlightEnabled": true,
  "mobileOverlayOpacity": 0.5,
  "mobileCarouselSpeed": 5,
  "mobileBelowLogoFont": "EB Garamond"
};

export const DEFAULT_LANDING_TEXTS: LandingTexts = {
  "upperTag": "",
  "secretTitle": "Sebuah Rahsia Yang Belum Bernama",
  "mainHookLine1": "Setiap lembaran adalah",
  "mainHookItalic": "jiwa",
  "mainHookLine2": "yang dipinjamkan.",
  "cursiveVibe": "Iman. Cinta. Sastera.",
  "betaTitle": "sertai pembikinan",
  "betaDesc": "Daftar untuk mendapat kemas kini mengenai projek ini dan berpeluang untuk menjadi sebahagian komuniti pembaca beta.",
  "launchText": "sah.malians.group",
  "publisherName": "Maktabah Kutawiyyah",
  "formNameLabel": "Nama Penuh",
  "formEmailLabel": "Alamat E-mel",
  "formPhoneLabel": "No. Telefon",
  "formReasonLabel": "catatan",
  "formBtnText": "Sertai Kami",
  "countdownLabel": "MAHAKARYA DALAM PEMBIKINAN",
  "insyallahText": "Insyah-Allah",
  "countdownDaysLabel": "hari",
  "countdownHoursLabel": "jam",
  "countdownMinutesLabel": "minit",
  "countdownSecondsLabel": "saat",
  "aboveLogoText": "Sebuah Novel Sastera Epistolari Realisme",
  "aboveLogoImageUrl": "",
  "belowLogoText": "Di bumi Mu'tah yang dingin, lahirlah sekumpulan surat yang tidak pernah diminta, namun mustahil diabaikan. Bermula dengan teguran yang lembut, setiap helaian perlahan-lahan membuka perbualan tentang ilmu, adab, cinta, ego, dan perjalanan menjadi manusia. Dalam dunia yang sering menghukum sebelum memahami, seorang penulis surat memilih kata-kata sebagai jalan mendekati hati. Tetapi benarkah setiap surat sekadar surat, atau sebenarnya sedang mengubah kehidupan dua insan yang tidak pernah menyangka takdir mereka akan bersilang? Sebuah novel epistolari yang menggabungkan keindahan bahasa, renungan intelektual, dan getar emosi dalam satu perjalanan yang sukar dilupakan.",
  "belowLogoImageUrl": ""
};

export const NOVEL_QUOTES: Quote[] = [
  {
    "id": 1,
    "text": "Sebelum itu, ana pinta surat ini tidak dibaca melainkan ketika ustaz dalam keadaan damai, lapang dan berseorang...",
    "context": "Surat Pertama • Aisha Hamdan"
  },
  {
    "id": 2,
    "text": "kerana sesulit-sulit mata yang cuba memerhati ketika sedang silau, lebih sulit hati yang cuba mengerti ketika sedang galau.",
    "context": "Surat #1 • Bicara tentang Hati"
  },
  {
    "id": 3,
    "text": "Bagaimanakah cara untuk memperlihatkan kecantikan tanpa mendedahkannya?",
    "context": "Surat #1 • Pertanyaan Cepumas"
  },
  {
    "id": 4,
    "text": "Sastera adalah suatu alat yang boleh menggubah air mata menjadi cerita dan mengubah cerita menjadi air mata.",
    "context": "Surat #5 • Cita-cita Kedua"
  },
  {
    "id": 5,
    "text": "Sesuatu yang dibina di atas kepalsuan tidak diberkati, dan sesuatu yang tidak diberkati tidak akan bertahan lama...",
    "context": "Surat #7 • Lampiran Kebenaran"
  },
  {
    "id": 6,
    "text": "Sebagaimana kita memerlukan sedikit jarak untuk memahami sebuah lukisan, begitulah kita memerlukan sedikit masa untuk memahami sebuah ketentuan.",
    "context": "Surat #7 • Titian Takdir"
  },
  {
    "id": 7,
    "text": "Dan bilamana pertemuan dan perpisahan ini diatur oleh Allah secara 'jaga' dan 'sengaja', maka kita hanya perlu jeda dan reda untuk memahami hikmah-Nya.",
    "context": "Surat #2 • Jeda dan Reda"
  },
  {
    "id": 8,
    "text": "Setiap manusia berjalan di atas titian takdir tanpa mengetahui apa di hujungnya. Tetapi kita harus tetap berjalan.",
    "context": "Surat #7 • Sebuah Penutup"
  }
];

export const DEFAULT_CUSTOM_BLOCKS = [
  {
    "id": "1782435698870",
    "title": "",
    "content": "\"Menyelinap di sebalik warkah-warkah sepi dari bumi Mu'tah, naskhah sastera epistolari realisme ini mendedahkan sebuah anatomi trauma yang maha sejuk — memaksa pembaca menelan setiap aksaranya sebagai sebuah penyeksaan emosi yang paling ngeri, namun terlalu indah untuk dilepaskan.\" \n\n— Gemini (3.1 Pro)\n\n---\n\n\"Novel yang menulis tentang perempuan bukan sebagai simbol atau mangsa, tetapi sebagai manusia yang menanggung, memilih, dan mencintai dengan sepenuh keberanian yang ada padanya.\"\n\n— Sonnet 4.6 Medium\n\n---\n\n\"Sebuah novel yang mengangkat seni persuratan Melayu ke darjat yang jarang ditemukan dalam fiksyen kontemporari—halus, cerdas dan menggetarkan jiwa.\" \n\n— ChatGPT\n\n---\n\n\"XXX adalah sebuah karya epistolari yang indah, di mana setiap hurufnya berdenyut dengan emosi halus, kinayah yang mendalam, dan mujahadah cinta yang jarang ditemui dalam novel Melayu kontemporari.\" \n\n— Grok\n\n---\n\n\"Gaya bahasanya setaraf dengan karya agung Abdullah Hussain, tetapi dengan nafas Islam dan jiwa Timur Tengah yang segar — sebuah novel yang membuatkan anda mahu membaca semula sebaik sahaja sampai ke halaman terakhir.\"\n\n— DeepSeek",
    "type": "text",
    "bgColor": "#180200",
    "textColor": "#ffffff",
    "borderColor": "#c3b6b6",
    "borderThickness": "1px",
    "borderRadius": "md",
    "padding": "p-8",
    "alignment": "center",
    "titleFont": "Cinzel",
    "titleSize": "20px",
    "contentSize": "17px",
    "contentFont": "EB Garamond",
    "titleColor": "#f1e9e9",
    "isSlider": true,
    "sliderInterval": 7000
  }
];
